### ISSUE TITLE
VMD didn't work in UE5.2?

### ISSUE THREAD

**Issue by Hotohori** [axilesoft/IM-for-UE5#6]
Could import PMX without a problem, but no matter what VMD I try it lead into a crash of the UE5 Editor after some minutes because my system runs out of memory (32GB RAM), the smaller the VMD is the longer it takes to get into that crash.

**Comment by axilesoft** [comment]
It had problem on 5.2,  but it should work in 5.2.1, try small vmd.

**Comment by Hotohori** [comment]
I tried it with a ~300kb one, same result. I'm on 5.2.1.

**Comment by axilesoft** [comment]
Not sure what's wrong. The latest main branch works for every vmd I tried in 5.2.1.

**Comment by Hotohori** [comment]
The opposite here. No clue what could be wrong. Did 5.1.1 also works fine? Then I will try it with that version and convert it to 5.2.1.

**Comment by axilesoft** [comment]
I did not test on 5.1.x . It may not work, the engine source code changed. 
And how do you import vmd, only select skeleton is enough, mesh is optional, others leave blank.

**Comment by Hotohori** [comment]
I give it up. I get it to work, but now wonder I have out of memory problems when the imported vmd (~5 mins long) is over 1,5GB big.

**Comment by axilesoft** [comment]
> I give it up. I get it to work, but now wonder I have out of memory problems when the imported vmd (~5 mins long) is over 1,5GB big.

Updated, should less than 1/30 size now.

**Comment by Hotohori** [comment]
Much better now, thanks. But the legs are not animated. Same pmx and vmd (MMDTool Box) exported with Blender FBX into UE5 works without this issue.

**Comment by axilesoft** [comment]
UE5 animation does not support leg-IK. Maybe FBX burn leg bone animation to legD bones. 
Does MMD has such plugin or tools to convert leg motion to legD ?

**Comment by axilesoft** [comment]
I released a tool to do this , not tested on other machine.
https://github.com/axilesoft/IM-for-UE5/releases/tag/vmd_tool_v0.1

**Comment by Hotohori** [comment]
Tried v0.1, pmx drag&drop works so far, but some vmd files didn't work, nothing happens on them when I drag&drop them at the window. Some other vmd files work.

Edit: And even that the vmd work in this program, it still didn't work in UE5.2, the legs are still not moving with IKLeg2D.vmd one.

Edit2: Tried it also with the actual IM-for-UE5 main source.

**Comment by axilesoft** [comment]
Does IKLeg2D.vmd has legD motion data ( 左足D, 左ひざD, 左足首D...) ? Check in MMD.
Could you upload the problem PMX and VMD to somewhere for me to test?

**Comment by Hotohori** [comment]
I didn't know MMD very well, can't find it. But the IKLeg2D.vmd works inside MMD, only not inside UE5.

PMX didn't matter, tried different and also tried the 1.pmx that was inside drs.zip inside UE5.

The single one didn't work at all (nothing happens when I drag and drop it on your app window) and the other two are that problem file that seems not to work converted: https://pics.blizado.de/vmd-test.zip

**Comment by axilesoft** [comment]
I can convert it. Drag the vmd into it directly, no PMX.
[hand in hand_IKLeg2D.zip](https://github.com/axilesoft/IM-for-UE5/files/12235427/hand.in.hand_IKLeg2D.zip)

Maybe char encoder problem, what's your system language ?

**Comment by Hotohori** [comment]
German. Maybe it is the problem, I don't think Win10 is the problem.

No, if I directly drag it in your convert app nothing happens with that vmd.

What should happen when I drag your two IKLeg2D files into your converter app? Because when I do there also nothing happens.

**Comment by axilesoft** [comment]
IKLeg2D in app will have wrong leg position, it's only for plugin to import.
I updated unicode encoder, you may try it .
https://github.com/axilesoft/IM-for-UE5/releases/tag/vmd_tool_v0.1

**Comment by Hotohori** [comment]
Still no reaction from your app with the hand in hand vmd, the world vmd still works and has now near the same size (some bytes smaller) than yours. The "forTest.vmd" works, the forTest_IKLeg2D.vmd is 99,4kb in size.

Maybe it helps you to look inside them: https://pics.blizado.de/forTest_IKLeg2D.zip

But I didn't had time yet to test them inside UE5.2.

**Comment by axilesoft** [comment]
The 2 files seems OK in UE5
